=== Drift2020/XML/ConsoleSeting/Tehnic/param.dtd
<!ELEMENT technics (product*)>
<!ELEMENT product (name,manufacturer,characteristics,price+,info_to_cred+)>

<!ELEMENT name (series,number)>
<!ELEMENT series (#PCDATA)>
<!ELEMENT number (#PCDATA)>

<!ATTLIST name
  name_is_firm CDATA #REQUIRED
  model CDATA #REQUIRED>


<!ELEMENT manufacturer (date+)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date
  day CDATA #REQUIRED
  month CDATA #REQUIRED
  year CDATA #REQUIRED>

<!ATTLIST manufacturer 
  name_of_country CDATA #REQUIRED>

<!ELEMENT characteristics (additional_characteristics,main_characteristics)>
<!ELEMENT additional_characteristics  (#PCDATA)>
<!ELEMENT main_characteristics (#PCDATA)>
<!ATTLIST characteristics
 power CDATA #REQUIRED>

<!ELEMENT price EMPTY>
<!ATTLIST price 
  price_retail CDATA #REQUIRED
  price_wholesale CDATA #REQUIRED>

<!ELEMENT info_to_cred EMPTY>
<!ATTLIST info_to_cred
  count_month CDATA #REQUIRED
  prise_of_month CDATA #REQUIRED>

=== Drift2020/XML/ConsoleSeting/Tehnic/prise_liist.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE technics SYSTEM "param.dtd">
<technics>
  <product >
    
    <name name_is_firm="PHILIPS" model="SH">
      <series>350</series>
      <number>3</number>
    </name>

    <manufacturer name_of_country="Germani">
      <date day="25" month="09" year="2016" />
    </manufacturer>

    <characteristics power="200mA/h">
      <additional_characteristics>la-la-la-la</additional_characteristics>
      <main_characteristics>bla-bla-bla-bla</main_characteristics>
    </characteristics>

    <price price_retail="899" price_wholesale="700"/>

    <info_to_cred count_month="8" prise_of_month="115"/>
    
  </product>
</technics>
